webpack_encore:
    output_path: '%kernel.project_dir%/public/build/default'
    builds:
        shop: '%kernel.project_dir%/public/build/shop'
        admin: '%kernel.project_dir%/public/build/admin'
        cms_shop: '%kernel.project_dir%/public/build/bitbag/cms/shop'
        cms_admin: '%kernel.project_dir%/public/build/bitbag/cms/admin'
        wishlist_shop: '%kernel.project_dir%/public/build/bitbag/wishlist/shop'
        wishlist_admin: '%kernel.project_dir%/public/build/bitbag/wishlist/admin'
        mollie-admin: "%kernel.project_dir%/public/build/admin"
        mollie-shop: "%kernel.project_dir%/public/build/shop"
    script_attributes:
        defer: false

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'

